---
namespace: myllynen
name: aap_automation
version: "1.1.5"
readme: README.md
authors:
  - Marko Myllynen <myllynen@redhat.com>
description: >
  Ansible playbooks and roles to install and upgrade Ansible Automation
  Platform using RPMs.
license:
  - GPL-3.0-or-later
tags:
  - aap
  - linux
  - configuration
  - infrastructure
dependencies:
  ansible.controller: ">=4.2.0"
  redhat.satellite: ">=3.6.0"
repository: https://www.github.com/myllynen/aap-automation
issues: https://www.github.com/myllynen/aap-automation/issues
