---
- name: Compare filetree configuration differences
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    controller_hostname: "{{ aap_install_controller_fqdn }}"
    #controller_username: "{{ aap_install_admin_username | default('admin') }}"
    #controller_password: "{{ aap_install_admin_password }}"
    controller_oauthtoken: "{{ lookup('file', lookup('env', 'PWD') + '/aap_ctrl_token_admin.txt') }}"
    controller_validate_certs: false

    controller_configuration_secure_logging: false
    controller_configuration_filetree_read_secure_logging: false
    controller_configuration_filetree_object_diff_secure_logging: false

    dir_orgs_vars: ./filetree_export
    orgs: Test Org
    env: common

    drop_user_external_accounts: true
  roles:
    - role: infra.controller_configuration.filetree_read
    - role: infra.controller_configuration.object_diff
      vars:
        aaacontroller_configuration_object_diff_tasks:
          - {name: workflow_job_templates, var: controller_workflows, tags: workflow_job_templates}
          - {name: job_templates, var: controller_templates, tags: job_templates}
          - {name: user_accounts, var: controller_user_accounts, tags: users}
          - {name: groups, var: controller_groups, tags: groups}
          - {name: hosts, var: controller_hosts, tags: hosts}
          - {name: inventory_sources, var: controller_inventory_sources, tags: inventory_sources}
          - {name: inventories, var: controller_inventories, tags: inventories}
          - {name: projects, var: controller_projects, tags: projects}
          - {name: credentials, var: controller_credentials, tags: credentials}
          - {name: credential_types, var: controller_credential_types, tags: credential_types}
          - {name: organizations, var: controller_organizations, tags: organizations}
    - role: infra.controller_configuration.dispatch
