---
- name: Install automation controller cli package
  hosts: bastion
  become: false
  gather_facts: true
  tasks:
    - name: Gather package facts
      package_facts:

    - name: Install automation controller cli package
      vars:
        installer_repo: >-
          ansible-automation-platform-{{ aap_install_version -}}
          -for-rhel-{{ ansible_facts.distribution_major_version -}}
          -{{ ansible_facts.architecture }}-rpms
      become: true
      yum:
        state: present
        name: automation-controller-cli
        enablerepo: "{{ installer_repo }}"
      when: "'automation-controller-cli' not in ansible_facts.packages"
